//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 05:27:21 PM MESZ 
//

package de.haw_hamburg.db;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the de.haw_hamburg.db package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: de.haw_hamburg.db
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Database }
	 * 
	 */
	public Database createDatabase() {
		return new Database();
	}

	/**
	 * Create an instance of {@link MessageType }
	 * 
	 */
	public MessageType createMessageType() {
		return new MessageType();
	}

	/**
	 * Create an instance of {@link MessagesType }
	 * 
	 */
	public MessagesType createMessagesType() {
		return new MessagesType();
	}

	/**
	 * Create an instance of {@link AccountType }
	 * 
	 */
	public AccountType createAccountType() {
		return new AccountType();
	}

}
