//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 11:00:26 AM CEST 
//


package de.haw_hamburg.db;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.haw_hamburg.db package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.haw_hamburg.db
     * 
     */
    private ObjectFactory() {
    }


    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public static AccountType createAccountType(String name,String password,String pop3server,int pop3port) {
        AccountType result=new AccountType();
        result.setName(name);
        result.setPassword(password);
        result.setPop3Server(pop3server);
        result.setPop3Port(pop3port);
        AccountType.Messages messages=new AccountType.Messages();
        messages.setMessage(new ArrayList<MessageType>());
        result.setMessages(messages);
        return result; 
    }

}
